## This notebook stands for reviewing some basics of NumPy

Here are some basic functions often used in data science use cases for data transformation or manipulation subjects.
In the following lines, I am showing those different ways to create an array. Sometimes I will share in which context of data analysis or data science it's possible some functions can be useful.

In [51]:
#import numpy library
import numpy as np

### Creating arrays based on different objects

In [52]:
#Create an array based on list
list1 = [1,2,3,4,5]
array_list = np.array(list1)
print("Nous obtenons la matrice à une ligne suivante:", array_list)

Nous obtenons la matrice à une ligne suivante: [1 2 3 4 5]


In [53]:
#Create an array based on a array
list2 = [[8,6,4,9],[2,3,6,9],[1,7,5,0]]
array = np.array(list2)
print("Nous obtenons la matrice suivante:\n", array)

Nous obtenons la matrice suivante:
 [[8 6 4 9]
 [2 3 6 9]
 [1 7 5 0]]


In [54]:
#Create an array based on a function
array = np.zeros((3,3))
print("Nous avons la matrice 0 suivante:\n",list3)

Nous avons la matrice 0 suivante:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
#Create an array based on a function 
array = np.ones((3,4))
print("Nous avons la matrice 1 suivante:\n",array)

Nous avons la matrice 1 suivante:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
#Create an identity array with a function
array = np.eye(4)
print("Nous avons la matrice identité suivante:\n",array)

Nous avons la matrice identité suivante:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
#Create an arrange array with a function
array = np.arange(11, 26, 3)
print("Nous avons la matrice suivante:\n",array)

Nous avons la matrice suivante:
 [11 14 17 20 23]


In [58]:
#Create an array with the linspace. This function is often used when generating points to designe some analytical graphics
#This function helps in generating values between two numbers and the number of points needed.
array = np.linspace(10,20,8)
print("Nous avons les points suivants:\n", array)

Nous avons les points suivants:
 [10.         11.42857143 12.85714286 14.28571429 15.71428571 17.14285714
 18.57142857 20.        ]


### Some Mathematics & Statistics functions often used in data science fields

In [59]:
#Create an array of random values with random function
#Helps in initializing weights of neuronnal networks and generating synthetic learning data (random data tables then)
array = np.random.random((2,3))
print("Nous avons la matrice suivante:\n", array)

Nous avons la matrice suivante:
 [[0.50586331 0.38688166 0.23056968]
 [0.76517649 0.10472565 0.29625244]]


In [30]:
#Some descriptives statistcs and mathematics funcitons often used in data science/analysis with numpy
#Defining an array based on a list
array = np.array([3,9,6,12])
print ("Nous avons la matrice suivante:", array)

#Functions
array_sum = np.sum(array)
print("La somme de ce vecteur est", array_sum)
array_mean = np.mean(array)
print("La moyenne de ce vecteur est", array_mean)
array_std = np.std(array)
print("L'écart type de ce vecteur est", array_std)
array_abs = np.abs(array)
print("La valeur absolue  de ce vecteur est", array_abs)
array_sqrt = np.sqrt(array)
print("Les racines carées de ce vecteur sont", array_sqrt)
array_min = np.min(array)
print("Le min de ce vecteur est", array_min)
array_max = np.max(array)
print("Le max de ce vecteur est", array_max)
array_power = np.power(array, 2)
print("La puissance carrée de ce vecteur est", array_power)
array_exp = np.exp(array)
print("La valeur exponentielle de ce vecteur est", array_exp)
array_log = np.log(array_abs)
print("Les logarithmes de ce vecteur sont", array_log)
array_sin = np.sin(array)
print("Les # sinus de ce vecteur sont", array_sin)
array_median = np.median(array)
print("La médiane de ce vecteur est", array_median)
#array_sum



Nous avons la matrice suivante: [ 3  9  6 12]
La somme de ce vecteur est 30
La moyenne de ce vecteur est 7.5
L'écart type de ce vecteur est 3.3541019662496847
La valeur absolue  de ce vecteur est [ 3  9  6 12]
Les racines carées de ce vecteur sont [1.73205081 3.         2.44948974 3.46410162]
Le min de ce vecteur est 3
Le max de ce vecteur est 12
La puissance carrée de ce vecteur est [  9  81  36 144]
La valeur exponentielle de ce vecteur est [2.00855369e+01 8.10308393e+03 4.03428793e+02 1.62754791e+05]
Les logarithmes de ce vecteur sont [1.09861229 2.19722458 1.79175947 2.48490665]
Les # sinus de ce vecteur sont [ 0.14112001  0.41211849 -0.2794155  -0.53657292]
La médiane de ce vecteur est 7.5


### Array manipulation
In the following lines, let's see how we can make some calculations on arrays with numpy. More, which analytic conclusion can we have?


In [108]:
array_mnp = np.array([[8,6,4],[2,3,6],[9,7,5]])

#Matrix Product
array_product = np.dot(array_mnp, array_mnp)
print("Le produit matriciel, nous donne:\n", array_product)

Le produit matriciel, nous donne:
 [[112  94  88]
 [ 76  63  56]
 [131 110 103]]


In [34]:
#Matrix Transpose
array_transpose = np.transpose(array_mnp)
print("La transposée de la matrice est \n", array_transpose)

La transposée de la matrice est 
 [[8 2 9]
 [6 3 7]
 [4 6 5]]


In [37]:
#Matrix inversion
array_inversion = np.linalg.inv(array_mnp)
print("La transposée de la matrice est \n", array_inversion)

La transposée de la matrice est 
 [[  6.75   0.5   -6.  ]
 [-11.    -1.    10.  ]
 [  3.25   0.5   -3.  ]]


In [107]:
#Determinant
array_det = np.linalg.det(array_mnp)
print("Le déterminant de la matrice est \n", array_inversion)

Le déterminant de la matrice est 
 [[  6.75   0.5   -6.  ]
 [-11.    -1.    10.  ]
 [  3.25   0.5   -3.  ]]


### Access matrix or vector for edition purposes and making updates of array under conditions

In [48]:
#Access the array elements
array=np.array([6,8,9,7,10])
first_value = array[0]
print("La première valeur est", first_value)
last_value = array[-1]
print("La dernière valeur est", last_value)

La première valeur est 6
La dernière valeur est 10


In [103]:
#Update an array
array[0] = 20
print("Le nouveau vecteur est", array)

Le nouveau vecteur est [20  8  9  7 10]


In [104]:
#Accessing an element under a condition
filter = array > 6
ifyes= array[filter]
print("Les éléments du vecteur qui respecte la condition sont", ifyes)

Les éléments du vecteur qui respecte la condition sont [20  8  9  7 10]


In [105]:
#Accessing the index of an element under a condition np.where function
condition = array > 6
index = np.where(condition)
print("Les indices du vecteur qui respecte la condition sont", ifyes)

Les indices du vecteur qui respecte la condition sont [20  8  9  7 10]


In [65]:
#Editing values of an array based on a condition
#when the condition 'condition = array > 6' is verified, replace the value by 0
array[condition] = 0
print("Le nouveau vecteur est", array)

Le nouveau vecteur est [ 0  8  9  7 10]


In [82]:
#Slicing and advanced indexation
sli_array = np.array([[5,7,9],[1,3,3],[2,9,0]])

#Slicing
first_row = sli_array[0, :]
first_col = sli_array[:, 0]
partial_array = sli_array[1:3 , 1:3]
print("La première ligne c'est", first_row ,"et la première colonne c'est",  first_col)
print("La sous matrice correspond à \n", partial_array)

#Advanced indexation
rows = [0, 1]
cols = [1, 2]
sltd_values = sli_array[rows, cols]
print("De façon avancé, les valeurs sélectionnées sont", sltd_values)

La première ligne c'est [5 7 9] et la première colonne c'est [5 1 2]
La sous matrice correspond à 
 [[3 3]
 [9 0]]
De façon avancé, les valeurs sélectionnées sont [7 3]


In [106]:
#Basic operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#addition
add = array1+array2
#product
product = array1*array2
print("Addition:", add,"\nProduct:", product)

Addition: [5 7 9] 
Product: [ 4 10 18]


In [88]:
#Broadcasting operation
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array4 = np.array([1, 2, 3])
print("la nouvelle matrice est \n", array3+array4)

la nouvelle matrice est 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


### Resize a matrix, add an element & knowing data types

In [95]:
#Resize an array
array5= np.arange(9)
resize= array5.reshape(3,3)
print("la nouvelle matrice est \n",resize)

la nouvelle matrice est 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [96]:
#Add a value in the array
array6 = np.append(array5, [10,14, 16])
print ("la nouvelle matrice est \n",array6)

la nouvelle matrice est 
 [ 0  1  2  3  4  5  6  7  8 10 14 16]


In [102]:
#Knowing array caracteristics
print("La dimension de la matrice est :",array3.shape)
print("le type d'objet est :", type(array3))
print("le type des élééments de l'objet est :", array3.dtype)

La dimension de la matrice est : (3, 3)
le type d'objet est : <class 'numpy.ndarray'>
le type des élééments de l'objet est : int64
